# Site
name: godesingbuild
description: Just another website
meta_description: Just another website
logo: /assets/images/logo.png
favicon: assets/images/gdbico.ico
paginate: 6
baseurl: "/godesignbuildtech"
email: 'hello@john.doe'
google_analytics: 
disqus:
sharethis:

# Authors
authors:
  michael:
    name: michael
    display_name: Michael
    image: /assets/images/michael.jpg
    email: hello@john.doe
    web: https://godesignbuild.tech
    twitter:
    description: Hi, I am Michael.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: john
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: godesignbuild by mike
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
